apiVersion: v1
kind: Namespace
metadata:
  name: portfolio-3d
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: portfolio-3d
  namespace: portfolio-3d
spec:
  replicas: 2
  selector:
    matchLabels:
      app: portfolio-3d
  template:
    metadata:
      labels:
        app: portfolio-3d
    spec:
      containers:
        - name: portfolio-3d-container
          image: adapaladocker/personal_portfolio_3d:development-4872810a9b8f0f8c5fd5878744ea1b278e3f0c7e
          ports:
            - containerPort: 80

          resources:
            requests:
              memory: "256Mi"
              cpu: "250m"
            limits:
              memory: "1Gi"
              cpu: "1"
      restartPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  name: portfolio-3d-service
  namespace: portfolio-3d
spec:
  selector:
    app: portfolio-3d
  ports:
    - protocol: TCP
      port: 8080 
      targetPort: 80
      nodePort: 30332
  type: NodePort
